sky:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: localhost
    port: 3306
    database: sky_take_out
    username: root
    password: admin123
  alioss:
    endpoint: https://oss-cn-hangzhou.aliyuncs.com
    access-key-id: LTAI5tDxcmgpPN73rFR5ft9d
    access-key-secret: 2JWGAZUaXYOqmn8jXzzYcoKy4wjnCB
    bucket-name: shallowdreams17
